library core;

export 'src/bridge/message_bridge.dart';
export 'src/protocol/message_protocol.dart';
export 'src/protocol/plugin_error_handler.dart';
export 'src/runtime/webview_host.dart';
export 'src/runtime/asset_server.dart';
export 'src/runtime/app_context.dart';
export 'src/utils/logger.dart';
export 'src/middleware/error_recovery.dart';
export 'src/middleware/circuit_breaker.dart';
export 'src/middleware/offline_queue.dart';
export 'src/security/bridge_auth.dart';
export 'src/security/message_signer.dart' hide ValidationResult;
export 'src/security/ssl_pinning.dart';
export 'src/security/content_security.dart';
export 'src/security/anti_tampering.dart';
export 'src/security/security_manager.dart';
export 'src/performance/benchmark_suite.dart';
export 'src/performance/binary_protocol.dart';
export 'src/performance/memory_profiler.dart';
export 'src/performance/performance_monitor.dart';
export 'src/performance/stream_handler.dart';
export 'src/performance/worker_isolate.dart';
export 'src/security/security_audit.dart';
