// ignore_for_file: avoid_print
import 'dart:io';

import 'package:yaml/yaml.dart';

import 'plugin_registry_data.dart';

/// پردازشگر sweetmelon.yaml
/// خروجی: لیست پلاگین‌های فعال و فایل‌های generate شده
class ConfigProcessor {
  final String configPath;
  late final Map<String, bool> _enabledPlugins;

  ConfigProcessor({this.configPath = 'sweetmelon.yaml'});

  /// خواندن config و parse
  Future<void> load() async {
    final file = File(configPath);

    if (!await file.exists()) {
      print('⚠️  sweetmelon.yaml not found, using defaults (all enabled)');
      _enabledPlugins = {
        for (final p in PluginRegistryData.allPlugins) p.id: true,
      };
      return;
    }

    final content = await file.readAsString();
    final yaml = loadYaml(content) as YamlMap;
    final plugins = yaml['plugins'] as YamlMap?;

    _enabledPlugins = {};

    for (final p in PluginRegistryData.allPlugins) {
      final pluginConfig = plugins?[p.id] as YamlMap?;
      final enabled = pluginConfig?['enabled'] as bool? ?? true;
      _enabledPlugins[p.id] = enabled;
    }
  }

  /// لیست پلاگین‌های فعال
  List<PluginDefinition> get enabledPlugins {
    return PluginRegistryData.allPlugins
        .where((p) => _enabledPlugins[p.id] == true)
        .toList();
  }

  /// لیست پلاگین‌های غیرفعال
  List<PluginDefinition> get disabledPlugins {
    return PluginRegistryData.allPlugins
        .where((p) => _enabledPlugins[p.id] != true)
        .toList();
  }

  /// Generate کردن service_locator.dart
  Future<void> generateServiceLocator() async {
    final enabled = enabledPlugins;
    final buffer = StringBuffer();

    buffer.writeln("// AUTO-GENERATED by sweetmelon config processor");
    buffer
        .writeln("// Do not edit manually. Run: dart run sweetmelon:configure");
    buffer.writeln("");
    buffer.writeln("import 'package:flutter/foundation.dart';");
    buffer.writeln("import 'package:get_it/get_it.dart';");
    buffer.writeln("");
    buffer.writeln("import 'package:sweetmelon/packages/core/lib/core.dart';");
    buffer.writeln(
        "import 'package:sweetmelon/packages/devtools/lib/devtools.dart';");
    buffer.writeln(
        "import 'package:sweetmelon/packages/performance/lib/performance.dart';");
    buffer.writeln(
        "import 'package:sweetmelon/packages/security/lib/security.dart';");
    buffer.writeln(
        "import 'package:sweetmelon/packages/plugin_engine/lib/plugin_engine.dart';");
    buffer.writeln("");

    // Imports
    for (final p in enabled) {
      buffer.writeln("import '${p.importPath}';");
    }

    buffer.writeln("");
    buffer.writeln("final sl = GetIt.instance;");
    buffer.writeln("");
    buffer.writeln("class ServiceLocator {");
    buffer.writeln("  static bool _initializing = false;");
    buffer.writeln("");
    buffer.writeln("  static Future<void> init() async {");
    buffer.writeln("    if (sl.isRegistered<MessageBridge>()) return;");
    buffer.writeln("    if (_initializing) return;");
    buffer.writeln("    _initializing = true;");
    buffer.writeln("");
    buffer.writeln("    try {");

    // Core registrations
    buffer.writeln(
        "      sl.registerLazySingleton<CacheManager>(() => CacheManager(maxEntries: 500));");
    buffer.writeln("      sl.registerLazySingleton<RateLimiter>(() {");
    buffer.writeln("        final limiter = RateLimiter();");
    buffer.writeln(
        "        limiter.setDefaultRule(RateLimitRule.perSecond(50));");
    buffer.writeln("        return limiter;");
    buffer.writeln("      });");
    buffer.writeln(
        "      sl.registerLazySingleton<ExecutionGuard>(() => ExecutionGuard(defaultTimeoutMs: 30000));");
    buffer.writeln("      sl.registerLazySingleton<PermissionManager>(() {");
    buffer.writeln(
        "        final manager = PermissionManager(cacheTtl: const Duration(minutes: 3));");
    buffer.writeln("        manager.setProvider(NativePermissionProvider(");
    buffer.writeln(
        "          fallbackStatus: kReleaseMode ? PermissionStatus.denied : PermissionStatus.granted,");
    buffer.writeln("        ));");
    buffer.writeln("        return manager;");
    buffer.writeln("      });");
    buffer.writeln(
        "      sl.registerLazySingleton<PluginRegistry>(() => PluginRegistry());");
    buffer.writeln(
        "      sl.registerLazySingleton<PluginManager>(() => PluginManager(");
    buffer.writeln("        registry: sl<PluginRegistry>(),");
    buffer.writeln("        permissionManager: sl<PermissionManager>(),");
    buffer.writeln("        rateLimiter: sl<RateLimiter>(),");
    buffer.writeln("        executionGuard: sl<ExecutionGuard>(),");
    buffer.writeln("        cacheManager: sl<CacheManager>(),");
    buffer.writeln("      ));");
    buffer.writeln("      sl.registerLazySingleton<MessageBridge>(() {");
    buffer.writeln("        final bridge = MessageBridge();");
    buffer.writeln("        final manager = sl<PluginManager>();");
    buffer.writeln("        bridge.setMessageHandler(manager.execute);");
    buffer.writeln("        bridge.setBatchHandler(manager.executeBatch);");
    buffer.writeln("        return bridge;");
    buffer.writeln("      });");
    buffer.writeln("      final bridge = sl<MessageBridge>();");
    buffer.writeln(
        "      sl<PluginRegistry>().setEventEmitter(bridge.emitEvent);");
    buffer.writeln("      sl.registerLazySingleton<WebViewHostConfig>(");
    buffer.writeln(
        "        () => kReleaseMode ? WebViewHostConfig.production() : WebViewHostConfig.development(),");
    buffer.writeln("      );");
    buffer.writeln(
        "      sl.registerLazySingleton<AssetServerConfig>(() => const AssetServerConfig());");
    buffer.writeln("      sl.registerLazySingleton<BridgeInspector>(");
    buffer.writeln(
        "        () => BridgeInspector(bridge: bridge, manager: sl<PluginManager>()),");
    buffer.writeln("      );");
    buffer.writeln("");
    buffer.writeln("      await _registerPlugins();");
    buffer.writeln("    } finally {");
    buffer.writeln("      _initializing = false;");
    buffer.writeln("    }");
    buffer.writeln("  }");
    buffer.writeln("");

    // Plugin registration
    buffer.writeln("  static Future<void> _registerPlugins() async {");
    buffer.writeln("    final registry = sl<PluginRegistry>();");
    buffer.writeln("    final emitter = registry.emitEvent;");
    buffer.writeln("");

    for (final p in enabled) {
      buffer.writeln("    await registry.register(${p.registrationCode});");
    }

    buffer.writeln("  }");
    buffer.writeln("");

    // Dispose
    buffer.writeln("  static Future<void> dispose() async {");
    buffer.writeln(
        "    if (sl.isRegistered<BridgeInspector>()) sl<BridgeInspector>().dispose();");
    buffer.writeln(
        "    if (sl.isRegistered<PluginManager>()) sl<PluginManager>().dispose();");
    buffer.writeln(
        "    if (sl.isRegistered<PluginRegistry>()) await sl<PluginRegistry>().dispose();");
    buffer.writeln(
        "    if (sl.isRegistered<CacheManager>()) sl<CacheManager>().dispose();");
    buffer.writeln(
        "    if (sl.isRegistered<MessageBridge>()) sl<MessageBridge>().dispose();");
    buffer.writeln("    await sl.reset();");
    buffer.writeln("  }");
    buffer.writeln("}");

    // Write file
    final outputFile = File('lib/di/service_locator.dart');
    await outputFile.writeAsString(buffer.toString());
    print(
        '✅ Generated: lib/di/service_locator.dart (${enabled.length} plugins)');
  }

  /// Generate کردن لیست Android permissions
  Future<void> generateAndroidPermissions() async {
    final enabled = enabledPlugins;
    final permissions = <String>{};
    final features = <String>{};

    // Core permissions
    permissions.add('android.permission.INTERNET');
    permissions.add('android.permission.ACCESS_NETWORK_STATE');

    for (final p in enabled) {
      permissions.addAll(p.androidPermissions);
      features.addAll(p.androidFeatures);
    }

    final buffer = StringBuffer();
    buffer.writeln('<!-- AUTO-GENERATED Android permissions -->');
    buffer.writeln(
        '<!-- Enabled plugins: ${enabled.map((p) => p.id).join(", ")} -->');
    buffer.writeln('');

    for (final perm in permissions.toList()..sort()) {
      buffer.writeln('    <uses-permission android:name="$perm"/>');
    }

    buffer.writeln('');

    for (final feat in features) {
      buffer.writeln(
          '    <uses-feature android:name="$feat" android:required="false"/>');
    }

    final outputFile =
        File('android/app/src/main/res/xml/generated_permissions.xml');
    await outputFile.parent.create(recursive: true);
    await outputFile.writeAsString(buffer.toString());

    print(
        '✅ Generated: android permissions (${permissions.length} permissions)');
    print('   Permissions: ${permissions.join(", ")}');
  }

  /// Generate iOS permissions
  Future<void> generateIosPermissions() async {
    final enabled = enabledPlugins;
    final iosPerms = <String, String>{};

    for (final p in enabled) {
      iosPerms.addAll(p.iosPermissions);
    }

    final buffer = StringBuffer();
    buffer.writeln('<!-- AUTO-GENERATED iOS permissions -->');
    buffer.writeln('<!-- Add these to ios/Runner/Info.plist -->');
    buffer.writeln('');

    for (final entry in iosPerms.entries) {
      buffer.writeln('    <key>${entry.key}</key>');
      buffer.writeln('    <string>${entry.value}</string>');
    }

    final outputFile = File('ios/generated_permissions.xml');
    await outputFile.writeAsString(buffer.toString());

    print('✅ Generated: iOS permissions (${iosPerms.length} entries)');
  }

  /// Generate dependency list for pubspec
  Future<void> generateDependencyReport() async {
    final enabled = enabledPlugins;
    final disabled = disabledPlugins;
    final deps = <String, String>{};

    for (final p in enabled) {
      deps.addAll(p.dependencies);
    }

    final removableDeps = <String, String>{};
    for (final p in disabled) {
      for (final dep in p.dependencies.entries) {
        // فقط اگه هیچ پلاگین فعال دیگه‌ای نیازش نداره
        final usedByOther = enabled.any(
          (ep) => ep.dependencies.containsKey(dep.key),
        );
        if (!usedByOther) {
          removableDeps[dep.key] = dep.value;
        }
      }
    }

    print('');
    print('📦 Dependency Report');
    print('────────────────────');
    print('');
    print('Required dependencies (${deps.length}):');
    for (final d in deps.entries) {
      print('  ✅ ${d.key}: ${d.value}');
    }

    if (removableDeps.isNotEmpty) {
      print('');
      print('Removable dependencies (${removableDeps.length}):');
      for (final d in removableDeps.entries) {
        print('  ❌ ${d.key}: ${d.value}');
      }
    }

    print('');
    print('Enabled plugins: ${enabled.length}');
    print('Disabled plugins: ${disabled.length}');
  }

  /// نمایش خلاصه
  void printSummary() {
    final enabled = enabledPlugins;
    final disabled = disabledPlugins;

    print('');
    print('🍈 Sweetmelon Plugin Configuration');
    print('═══════════════════════════════════');
    print('');
    print('✅ Enabled (${enabled.length}):');
    for (final p in enabled) {
      print('   • ${p.id.padRight(20)} — ${p.description}');
    }

    if (disabled.isNotEmpty) {
      print('');
      print('❌ Disabled (${disabled.length}):');
      for (final p in disabled) {
        print('   • ${p.id.padRight(20)} — ${p.description}');
      }
    }
  }
}
