import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase configuration.
///
/// The real values are generated by the FlutterFire CLI
/// (`flutterfire configure`) from an actual Firebase project. These
/// placeholders keep the project buildable and analyzable; replace them with
/// the generated file when wiring up a real Firebase project.
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:1234567890:android:placeholder',
    messagingSenderId: '1234567890',
    projectId: 'sweetmelon-placeholder',
    storageBucket: 'sweetmelon-placeholder.appspot.com',
  );
}
